### ISSUE TITLE
M18 Combat Uniform

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#12]
shouldn't the chest area of the uniform be a blank green color like the other uniforms?
Top Image M18
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/75e4dab9-3c9d-4811-8791-be12dea7627f)
Bottom Image Flecktarn
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/2f7a5cbd-9a9a-4909-967e-7d26d902880d)

**Comment by Kartsaa** [comment]
No, Bulgarian M18 uniforms have camo chests as well most of the time.
