### ISSUE TITLE
POST MISSING ICON FILES HERE

### ISSUE THREAD

**Issue by Kartsaa** [Kartsaa/PB_Rework#15]
Post all missing icon file errors here, rather than making their own issue for each one.

**Comment by CapryCorn** [comment]
Gevaer M10 A4 - no inventory icon
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/9ed59ae8-d252-4a98-83c0-50cc14aed969)

**Comment by Kartsaa** [comment]
> Gevaer M10 A4 - no inventory icon ![image](https://private-user-images.githubusercontent.com/53835641/317476776-9ed59ae8-d252-4a98-83c0-50cc14aed969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDY2NzEsIm5iZiI6MTcxMTYwNjM3MSwicGF0aCI6Ii81MzgzNTY0MS8zMTc0NzY3NzYtOWVkNTlhZTgtZDI1Mi00YTk4LTgzYzAtNTBjYzE0YWVkOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNGIwMjYyZTliODUwYjlhMDNiYTQ4YWMxZmRhYmFkNjEyNjA4MjAyYzQ5M2I0YmRhOWNlZDdkODdjYTEwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xCTUIKaCfLHGPaxf4Ki2FGaND0pue3KFs3qUQzrPJ64)

Not bug, have not done icon for it yet.
