### ISSUE TITLE
M90 Ops Core Fast Helmet (non Headset variant) 

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#17]
M90 Ops Core Fast Helmet (non Headset variant) went a little too fast and brought a future black headset with him that isn't textured lol
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/e5de46f2-9b15-44b9-8766-d1437590a0da)

**Comment by Kartsaa** [comment]
fixed
