### ISSUE TITLE
Multicam Backpack

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#19]
-Eagle Backpack reskins are a touch too dark compared to the other multicam equipment

too dark
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/293a6183-ed23-4def-8f26-aa7a96d56ff5)

just right
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/dccc6bd3-4957-4238-8665-3a92ae3ce5c6)

**Comment by CapryCorn** [comment]
Actually this seems to be with every "Backpack" and "Medic Backpack" version

**Comment by Kartsaa** [comment]
All fixed
