### ISSUE TITLE
French Autorifleman

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#22]
honestly no clue how you managed to equip a SU-230 and an Aimpoint at the same time 
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/ecc00b21-772d-4638-a329-adcc7f392a95)

**Comment by CapryCorn** [comment]
(once you spawn in, it's only the SU-230 equipped)

**Comment by Kartsaa** [comment]
My brother in christ, you have two units on top of each other.
(See the 4 sets of hands and 2 sets of guns)

**Comment by CapryCorn** [comment]
interesting 🤔

**Comment by Kartsaa** [comment]
(The two dudes just had same spawn coordinates)
