### ISSUE TITLE
Vodoo Scope

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#31]
Smol issue with the edges (left/right) on the Vodoo scope (maybe just with 21:9 ? ). Once you see it marked with the red circles, you can never unsee it again

![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/13e1f23e-cdd6-452c-bce9-12885b8deffc)

**Comment by Kartsaa** [comment]
Skbidi fixed
