### ISSUE TITLE
French C-130

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#37]
You could probably get away with the mirroring issue by using letters like b/d, i, l, o, v, w, x, and Numbers like 1, 8, 0 (depending on the font used)
![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/29c71643-e397-4946-977e-a2e953520979)

**Comment by Kartsaa** [comment]
I've base all on a real French C-130. Will stay as is for now
