### ISSUE TITLE
M1113 M2

### ISSUE THREAD

**Issue by CapryCorn** [Kartsaa/PB_Rework#44]
UN Camo for the M2 gun is a little scuffed (i.e. the gun armor) ![image](https://github.com/Kartsaa/PB_Rework/assets/53835641/002527fe-ccfb-4269-ac44-0b34cf3610cd)

**Comment by Kartsaa** [comment]
Interesting, the gun armor version of this should not exist for UN

**Comment by Kartsaa** [comment]
accidental close woops

**Comment by Kartsaa** [comment]
Added shield variant to UN M113
